// Custom Errors
export enum PatientErrorCode {
  // Validation Errors (400)
  PATIENT_VALIDATION_FAILED = 'PATIENT_VALIDATION_FAILED',
  INVALID_DATE_OF_BIRTH = 'INVALID_DATE_OF_BIRTH',
  INVALID_PHONE_FORMAT = 'INVALID_PHONE_FORMAT',
  INVALID_PINCODE_FORMAT = 'INVALID_PINCODE_FORMAT',
  INVALID_EMAIL_FORMAT = 'INVALID_EMAIL_FORMAT',
  INVALID_GENDER_VALUE = 'INVALID_GENDER_VALUE',
  INVALID_BLOOD_GROUP = 'INVALID_BLOOD_GROUP',

  // Business Logic Errors (409)
  PATIENT_ALREADY_EXISTS = 'PATIENT_ALREADY_EXISTS', // Same phone/email
  DUPLICATE_PATIENT_RECORD = 'DUPLICATE_PATIENT_RECORD',

  // Not Found Errors (404)
  PATIENT_NOT_FOUND = 'PATIENT_NOT_FOUND',
  PRIMARY_DOCTOR_NOT_FOUND = 'PRIMARY_DOCTOR_NOT_FOUND',

  // Authorization Errors (403)
  PATIENT_ACCESS_DENIED = 'PATIENT_ACCESS_DENIED',

  // Dependency Errors (422)
  REFERENCED_DOCTOR_INACTIVE = 'REFERENCED_DOCTOR_INACTIVE',
  PATIENT_HAS_ACTIVE_APPOINTMENTS = 'PATIENT_HAS_ACTIVE_APPOINTMENTS',

  // Server Errors (500)
  PATIENT_CREATION_FAILED = 'PATIENT_CREATION_FAILED',
  PATIENT_UPDATE_FAILED = 'PATIENT_UPDATE_FAILED',
  PATIENT_DELETION_FAILED = 'PATIENT_DELETION_FAILED',
}
